language: cpp
os: osx
arch: arm64

jobs:
  include:
    - stage: Install brew deps
      name: Installing deps with homebrew
      script: |
        brew install cmake ninja make lua
    - stage: Install vcpkg
      name: "Install vcpkg"
      script: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install glfw3 imgui imgui[opengl3-binding,glfw-binding,freetype] glad gl3w stb openal-soft libsndfile freetype lua zstd 7zip sol2 nlohmann-json assimp soil opencv nativefiledialog gtest
    - stage: Configure project and building it
      name: "Configure, build and testing project"
      script: |
        cd $TRAVIS_BUILD_DIR
        make